### ISSUE TITLE
drm command line options do not work as documented

### ISSUE THREAD

**Issue by gonsie** [hpc/mpifileutils#193]
Seems like the `--match` and `--exclude` options are doing the opposite of what the documentation says.

Running `drm --dryrun -v --name --match file_*` has no output (other than "Walking ...") indicating that no files are deleted.

Running `drm --dryrun -v --name --exclude file_*` prints
```
Type=REG File=/p/lustre1/gonsie/file_00000007
Type=REG File=/p/lustre1/gonsie/file_00000008
Type=REG File=/p/lustre1/gonsie/file_00000016
Type=REG File=/p/lustre1/gonsie/file_00000017
Type=REG File=/p/lustre1/gonsie/file_00000022
Type=REG File=/p/lustre1/gonsie/file_00000023
Type=REG File=/p/lustre1/gonsie/file_00000031
```
meaning that those are deleted (which is the opposite of what exclude should do).

Also, the final status "Walked 353 files in ..." is misleading. Those are the items that matched the regex, not the total number of items analyzed.

**Comment by adammoody** [comment]
Yeah, this is a touchy option, because it takes POSIX regex syntax (from regexec) rather than shell regex.  Also, you have to be sure the shell is not interpreting things before it gets passed to the command.  I think the following would be the right syntax:

```
drm --dryrun -v --name --match 'file_.*' /p/lustre1/gonsie/*
```

Note the single quotes to prevent the shell from expanding the "*" and the added "." to tell the regex that you want any character repeated, rather than zero or more of "_".  Also, I added the /p/lustre1 argument to provide the paths to be walked, from which to then match or exclude items.

We should think about this interface, since the syntax mix up is easy to do, and as you have shown, it can lead to exactly the wrong result.

**Comment by dsikich** [comment]
@gonsie @adammoody 

Added a note to the drm page about not using shell here: https://mpifileutils.readthedocs.io/en/latest/drm.1.html
