### ISSUE TITLE
readthedocs not getting updated

### ISSUE THREAD

**Issue by gonsie** [hpc/mpifileutils#196]
It looks like the last readthedocs build was over a month ago... I'm not sure why it's not getting updated with the latest commits on master. @dsikich is the maintainer... maybe she can add me to the project on RTD?

**Comment by adammoody** [comment]
We'll also likely want a way to point readthedocs to different versions of the docs.  The interface and behavior of some tools changes across releases, and we'll want users to be able to find the docs corresponding to their version of the tools.

**Comment by dsikich** [comment]
@gonsie @adammoody Eh yeah "latest" was not pointing to a branch in the repo. It is now pointing to master, and that kicked off a build since there was a commit after the last build readthedocs did.

We can associate tagged versions of the project with readthedocs from what I can tell. Although I'm not sure how I would add you to my readthedocs.org account. It doesn't look like there is an option for that. The other option would be to use your readthedocs.org account, and get it synced with the web hook. 

What tagged versions of the tools do we want docs built for specifically? One issue that may come up is we only recently switched to RTD so the old tagged versions will not contain the docs folder with the .rst files to build. But we can start this process for a tagged version of 0.8?

**Comment by dsikich** [comment]
@gonsie @adammoody Closing this issue. readthedocs is now being updated properly. It will kick off a build for v0.8 when something is pushed, and for the master branch. We were not using readthedocs for 0.7 so we won't be able to link that version on the page currently.
