### ISSUE TITLE
parallel dcp for a single large file?

### ISSUE THREAD

**Issue by adilger** [hpc/mpifileutils#281]
It isn't stated in the `dcp.1` man page (so I guess at minimum it could be considered a defect therein) whether `dcp` is doing parallel data read and/or write when running on a single large file?  The man page only talks about doing parallel directory traversal, nor does `dcp` have arguments like `--chunksize` or  `--stripe-size` or equivalent that would indicate it is splitting a single file into segments.

I tried finding this out by looking at the code in `mfu_copy_file()`, and it at least _seems_ like a single file could be copied in parallel, but it isn't clear where the parameters for this function come from.

**Comment by adammoody** [comment]
Thanks, @adilger .  Yes, both dcp and dcp1 will copy a single large file in parallel, and yes we need to update our documentation to make this clear.  They each logically slice files at 1MB chunk boundaries and copy file data in units of those chunks.  If you're interested in looking for the current implementation details, see below.

With dcp, the set of source files are logically sliced into chunks which are then distributed in even portions to processes in a static work assignment.  The logic for slicing up a set of files is here:

https://github.com/hpc/mpifileutils/blob/master/src/common/mfu_flist_chunk.c#L38 

This gets called from dcp --> mfu_flist_copy --> mfu_copy_files --> mfu_file_chunk_list_alloc

The chunk size is given as a field in the copy_opts structure.  We currently are missing an option in dcp to change this.  The chunk size defaults to 1MB:

https://github.com/hpc/mpifileutils/blob/master/src/common/mfu_flist_copy.c#L2495

With dcp1, the logical chunks are created and distributed in a more dynamic, random fashion using libcircle.

We ended up with two implementations, because the random work stealing in libcircle could lead to lots of contention on Lustre byte range locks when copying a large single file.  The static work assignment tends to work better there.  Our ultimate goal is to support both algorithms (static and dynamic) in a single tool and to pick the best algorithm depending on the situation.  As another optimization, one could imagine using a different chunk size per file, e.g., slice files based on Lustre stripe size, which could be different for each file being copied.

**Comment by adilger** [comment]
Adam,
definitely using the larger of the stripe size, the RPC size, and/or a larger fixed chunks (eg. 4MB) will reduce locking contention with Lustre.   We find at least 4MB or 8MB RPCS are needed to get maximum performance with the backend storage, and in some cases performance continues to improve incrementally up to 16MB.

I could take a crack at wiring up a --chunksize option so that this is more easily tested.

It isn't clear to me whether "dcp" or "dcp1" is the future direction of the code, and which one should get the most attention?  Both seem to have had commits since they were forked. 

Cheers, Andreas

**Comment by adilger** [comment]
I've created PR #282 to add the --chunksize and --blocksize options.

Improving the default values (probably 4MB), and adding automatic Lustre stripe-size detection should go in a separate patch, but I'm not sure how best to change this.  Is 1MB tried-and-true best performing, or just  a default chosen because that is the default Lustre stripe size?  Should the stripe size override the default values, if available, or should there be something like "--chunksize=0" to enable that?

**Comment by adilger** [comment]
This was fixed via PR#284.
