### ISSUE TITLE
dcp: add --dereference option as in cp to copy original files instead of links

### ISSUE THREAD

**Issue by adammoody** [hpc/mpifileutils#29]
Some have requested an option to copy the source file the link points to rather than the link.

**Comment by lancewilson-monash** [comment]
Would add that this would be very useful

**Comment by daltonbohning** [comment]
@adammoody It seems DAOS has need of this feature. In addition, DAOS has need of "copying broken links".
`cp` and `dcp` handle copying symlinks somewhat differently.
- `dcp` will traverse the link (using `access`) and only copy the link if the link value is accessible (no broken links)
- `cp --no-dereference` will simply copy the link, even if the link value might be inaccessible or broken.
  - DAOS has need of this, since links between POSIX/DFS/DFUSE might invalid in different contexts.

I'm thinking this proposal would be useful for DAOS, add new features for the general case, and still be backwards compatible:
- Default - Just as it currently is. symlinks will be copied only after a successful `access` call
- `--dereference` - Instead of copying links, copy the values pointed to
- `--no-dereference` - Copy the symlinks, _without_ an `access` call

**Comment by daltonbohning** [comment]
For implementing `--dereference` it seems `walk_stat_process` would need some modification.
Here, if the path is a directory, it is recursed into. We would need to do something similar with symlinks, where we follow the value of the symlink, and either process the file it points to or recurse into the directory it points to.
https://github.com/hpc/mpifileutils/blob/871d8f7d96ae01d1bf66c7e9751884f3824ee368/src/common/mfu_flist_walk.c#L539-L555

Then, I think we should _**not**_ call this for when we traverse the symlink:
https://github.com/hpc/mpifileutils/blob/871d8f7d96ae01d1bf66c7e9751884f3824ee368/src/common/mfu_flist_walk.c#L534-L537

**Comment by adammoody** [comment]
Yes, I think this is still a feature a lot of people could benefit from.

We'll need to be careful to handle the path to each item properly when going through a symlink.  For example, some mfu functions match each item against a list of source paths that the user specified, e.g., to compute the relative path to an item from its source path to which a destination path is then prepended.  In this case, we'll want to continue to match using the path to the item through its symlink, rather than the resolved path to the item.  We should also double check whether there might be spots where we need the resolved path (not sure).  It's possible this all of this just works, but this is one thing to keep in mind.

**Comment by daltonbohning** [comment]
I agree. I've seen some places that will need special attention. I'm going to need to first step through this code some more to make sure I understand the bigger picture before moving forward. I'll let you know of any issues that may need to be addressed.
