### ISSUE TITLE
Completing sparse file capability

### ISSUE THREAD

**Issue by shawnahall71** [hpc/mpifileutils#294]
Hi,

We'd love to use mpiFileUtils, but the one major missing feature that's preventing us from doing so is sparse file support.  There's a chance we could contribute development effort toward this, but we need to get an idea of the scope first.

Does anyone have an estimate of the developer time needed to implement sparse file support in dcp and dsync?

**Comment by adammoody** [comment]
Hi @shawnahall71 !  Same Shawn that I know?

Thanks for your interest.  We certainly always welcome contributions to the project if you'd like to pitch in.

@LiXi-storage added our original support for sparse files in dcp.  That logic is in the mfu_flist_copy() routine, which is called from both dcp and dsync.  It runs through the sparse file logic when the mfu_copy_opts->sparse flag is set to 1.  The heavy lifting is dong in the copy_fiemap routine here:

https://github.com/hpc/mpifileutils/blob/2de9b3076cc7738eeae68a3d0000f408620bc308/src/common/mfu_flist_copy.c#L1724

With dcp, you can attempt to use this with the -S option.

The last we looked at this from LLNL, our systems did not seem to support the ioctl for fiemap to look up file extents, so that we couldn't test the code.

@LiXi-storage , do you have any ideas on what it would take to get this up and going again?

**Comment by shawnahall71** [comment]
Hi @adammoody!  Yes, same Shawn.  Looking forward to this year's "super-Panda" story ;-)

That's great!  I had seen the contributions from @LiXi-storage, but didn't realize that was relatively complete other than wiring up the CLI options.

- It sounds like you haven't been able to use this at LLNL because you're running ZFS underneath, and the fiemap ioctls don't work for that combo? http://lists.lustre.org/pipermail/lustre-discuss-lustre.org/2015-August/013006.html and https://github.com/zfsonlinux/zfs/issues/264.
- So based on Andrea's comment, it sounds like it does work for ldiskfs based filesystems?
- The only trouble is that although we're entirely ldiskfs at the moment, we're also fully PFL which then yet again breaks fiemap? https://jira.whamcloud.com/browse/LU-11848

**Comment by adammoody** [comment]
Well, good to hear from you, @shawnahall71 !  Unfortunately, I don't know if I'll make MUG this year, so I'm hoping someone can carry on the super-Panda talks.

Thanks for sharing your findings on when that will and will not work.  That helps shed some light on things.

Thinking about our code more, we've got both read and write optimizations to deal with sparse files.

On the read side, we use the file extents to just deal with those portions of the file that have extents.  That logic is in the mfu_copy_file_fiemap function.  This routine should fall back to use a normal copy if it fails to find the extents.

Then during the write, there is a test to see if the data block to be written consists of all zeros.  If so, it avoids writing that particular block to the file when the sparse option is enabled.  That logic for that is here:
https://github.com/hpc/mpifileutils/blob/2de9b3076cc7738eeae68a3d0000f408620bc308/src/common/mfu_flist_copy.c#L1628

So I think the sparse option should still provide a benefit, even on file systems that do not support querying for the file extents.  I know @LiXi-storage had this working when it was originally committed.  However, parts of the code may have been changed since then, and we can't easily test it at LLNL.

I'd say it's worth a shot if you're up for giving it a try.

**Comment by shawnahall71** [comment]
Hi Adam,

I've done a bit of testing today, and it does appear the fallback method works as you described.  For reading, the entire apparent size of the sparse file is read, but when writing only blocks with data are written.  The resulting files end up with a small overhead of extra blocks that were written, presumably due to the chunking.  md5sum shows that the files are identical.

I think this will be a good tool to have in the tool belt.  There are a few things on my wishlist (dsync sparse option, Lustre FIEMAP support for PFL, and ability for dynamic/static work assignment options in one tool as mentioned in #241), but it seems like it will do the job for the moment.

Also worth mentioning - I tested the hidden -g option in dcp to trigger the Lustre group lock.  As expected it increased performance on the copy.  Didn't run into any issues using it.

**Comment by adammoody** [comment]
Great!  Thanks.  Good to hear that the sparse option is working as we hoped in the fallback case, and good to know that the -g option is working, as well.

For the write case, I think adding a sparse option to dsync should be straight-forward, but I haven't looked in detail yet.  It may just be a matter of handling the option from the command line and then setting the sparse flag during the call to mfu_flist_copy.  The read case when comparing byte regions between source and destination files might require more significant development work.

Please go ahead and create some issues for your wishlist requests so we can track those.

**Comment by adammoody** [comment]
Got a PR in the works to add --sparse to dsync: https://github.com/hpc/mpifileutils/pull/298/files

**Comment by adammoody** [comment]
Merged https://github.com/hpc/mpifileutils/pull/298.  This at least supports reading/writing sparse files as with dcp when copying files from source to destination.

There are other aspects of dsync where it would be beneficial to handle sparse files.  In particular, we could only read file extents when doing a ```dsync --contents``` which compares byte regions of files.  That functionality would also be useful in dcmp.

**Comment by adammoody** [comment]
@shawnahall71 , with the merge of the above PR, I'll close this ticket out.  I have created a few other tickets to deal with other sparse file optimizations that come to mind.

Please open new issues for the other items if you'd like so we can track those separately.
