### ISSUE TITLE
daos: investigate potential daos_mknod as open/close

### ISSUE THREAD

**Issue by adammoody** [hpc/mpifileutils#353]
The mfu_mknod is not critical to dcp, but it may be required on other tools.  This is lower priority, but if dfs has no mknod, I'm wondering if it can be emulated with a dfs_open/dfs_close.

**Comment by daltonbohning** [comment]
@dsikich 
I'm going to look into this, since I see minor errors cropping up when using dcp with a dfuse mounted path.
I.e. mfu_flist_copy -> mfu_create_file -> mfu_file_mknod
throws an error about the operation now being supported.

**Comment by dsikich** [comment]
@daltonbohning can you share the error output here?

**Comment by daltonbohning** [comment]
**Setting up the pool/container**
dmg pool create -s 1G -n 10G
export pool1=9dec0f4a-f5be-451d-9570-619641aeb37c
daos cont create --svc 0 --pool $pool1 --type POSIX --path /tmp/dbohninx/uns/p1cont1
export p1cont1=073e8a48-43ae-4732-ba94-5c520df1a878
dfuse --svc 0 --pool $pool1 --cont $p1cont1 -m /tmp/dbohninx/p1cont1

**Contents of source directory**
ls /tmp/dbohninx/s
dir1  file1

**Copying**
dcp /tmp/dbohninx/s /tmp/dbohninx/p1cont1

**The error**
[/home/dbohninx/mpifileutils_dev/mpifileutils/src/common/mfu_flist_copy.c:1140] ERROR: File `/tmp/dbohninx/p1cont1/s/file1' mknod() failed (errno=38 Function not implemented)

**Corresponding code**
https://github.com/daltonbohning/mpifileutils/blob/6f4a6d3252b720c770ed2bcb64c99dac3ae9f2bf/src/common/mfu_flist_copy.c#L1128-L1144

**Result dfuse directory**
ls /tmp/dbohninx/p1cont1/s
dir1  file1

The result appears to be fine, but the error is still thrown, presumably because dfuse doesn't have mknod implemented.
Of course, mfu_file_mknod switches between daos_ and mfu_ functions, BUT, this is a dfuse mounted path, so it appears to mpifileutils as a POSIX path, and therefore mfu_mknod is called and dfuse hasn't implemented it.

**Another direct example (not using dcp)**
mknod /tmp/dbohninx/p1cont1/some_file p
mknod: ‘/tmp/dbohninx/p1cont1/some_file’: Function not implemented

**Comment by daltonbohning** [comment]
https://github.com/hpc/mpifileutils/pull/378

This adds daos_mknod, but dfs itself still does not have a mknod function, so the "errors" still appear for a dfuse mounted DAOS destination.

**Comment by daltonbohning** [comment]
Moved the `dfuse`-specific discussion to #381
