### ISSUE TITLE
Finding dependencies in distro standard locations

### ISSUE THREAD

**Issue by brianjmurrell** [hpc/mpifileutils#394]
I don't know cmake very well, so I could be way off here, but I believe the `-DWITH_*_PREFIX` options are expecting to be given a directory under which `include/`, `lib[64]/`, etc. directories will be found with the content of the dependency.

But that's not how MPI packages are packaged on EL7.  They are split between `/usr/lib64/$mpi/` and `/usr/include/$mpi-$arch/` as such:

```
$ ls -l /usr/lib64/mpich/
total 12
drwxr-xr-x. 2 root root 4096 Sep 28 20:25 bin
drwxr-xr-x. 3 root root 4096 Sep 28 20:25 lib
drwxr-xr-x. 3 root root 4096 Jun 19 12:17 share
$ ls -l /usr/include/mpich-x86_64/
total 304
drwxr-xr-x. 2 root root   4096 Sep 28 20:25 json-c
-rw-r--r--. 1 root root 140506 Sep 16 12:58 mpi.h
-rw-r--r--. 1 root root 101184 Sep 16 12:58 mpicxx.h
-rw-r--r--. 1 root root  20300 Sep 16 12:58 mpif.h
-rw-r--r--. 1 root root  26336 Sep 16 12:58 mpio.h
-rw-r--r--. 1 root root   1177 Sep 16 12:58 mpiof.h
```

Unfortunately, I don't know enough about cmake to try to hack this kind of thing in.

Any ideas?

**Comment by daltonbohning** [comment]
I don't think there is an option to include a path for MPI. I think MPI is "automatically" looked for and included.
If needed, I think we can modify `SetupMPI.cmake` to allow a configurable version number.

For an explanation on how the MPI libraries are found:
`CMakeLists.txt` has this:
https://github.com/hpc/mpifileutils/blob/fb5b43cd703bdf4d2857238fb5969525e688242b/CMakeLists.txt#L72-L75
Which uses `SetupMPI.cmake`, which does this:
https://github.com/hpc/mpifileutils/blob/fb5b43cd703bdf4d2857238fb5969525e688242b/cmake/SetupMPI.cmake#L47
`find_package(<name>)` tells `cmake` to look for `Find<name>.cmake`, which I believe should be included in the `cmake` installation. For my installation, this is in:
`/usr/share/cmake3/Modules/FindMPI.cmake`

**Comment by brianjmurrell** [comment]
It seems that alternatively, one can define the include dir and libs individually:

```
$ cmake3 ../ -DDTCMP_INCLUDE_DIRS=/usr/include/mpich-x86_64          \
             -DDTCMP_LIBRARIES=/usr/lib64/mpich/lib/libdtcmp.so      \
             -DLibCircle_INCLUDE_DIRS=/usr/include/mpich-x86_64      \
             -DLibCircle_LIBRARIES=/usr/lib64/mpich/lib/libcircle.so
```

It might be nice if cmake could figure these paths out by itself, given that they are standard on EL7.

**Comment by daltonbohning** [comment]
It seems this works for `LibCircle_INCLUDE_DIRS` by just setting a hint.
```
FIND_PATH(LibCircle_INCLUDE_DIRS
    NAMES libcircle.h
    HINTS ${WITH_LibCircle_PREFIX}/include ${MPI_C_INCLUDE_PATH}
)
```

I'm still trying to find a clean and compatible solution for `LibCircle_LIBRARIES`

**Comment by daltonbohning** [comment]
I have tried to find a clean solution for setting `LibCircle_LIBRARIES` automatically, but I have not been able to find a clean solution. The closest I found was this:
https://gitlab.kitware.com/cmake/cmake/-/issues/17434

But that solution will not work in the general case, and certainly not in our case. I think part of the issue is that there might be different versions of openmp/mpich, and also lib vs. lib64, which maybe is why FindMPI.cmake doesn't expose any sort of `MPI_C_LIBRARY_PATH`, similar to `MPI_C_INCLUDE_PATH`.

As far as I can tell, I think this might actually be the best solution:
```
-DLibCircle_INCLUDE_DIRS=/usr/include/mpich-x86_64      \
-DLibCircle_LIBRARIES=/usr/lib64/mpich/lib/libcircle.so
```
Even looking at the [libcircle.spec](https://github.com/daos-stack/libcircle/blob/master/libcircle.spec), this library path is built based on the mpi distro and version, so I think maybe it makes sense to have to also specify that same path here.
