### ISSUE TITLE
daos: remove svc rank list from dcp

### ISSUE THREAD

**Issue by dsikich** [hpc/mpifileutils#426]
It is no longer required that a svc level be specified when connecting to a DAOS Pool, so it would be best to remove this from the dcp code. The reason being that it cuts down on the number of arguments that are required (and there are already so many). The other proposal would be to make it an option argument, but that would require adding preprocessor macros to call libdaos API calls with the correct arguments, since the libdaos API is changing (i.e. daos_pool_connect).

**Comment by daltonbohning** [comment]
For what it's worth, I created an internal ticket DAOS-6097 to keep track of this.
Internally, I believe that step 1 is to make svc optional, and step 2 is to remove it entirely from tools.
I think the best approach would be to remove the svc entirely, since that seems to be the direction we are headed.

**Comment by dsikich** [comment]
@daltonbohning great, yes I would prefer to just remove it as well.
